//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyAppointer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobOwners
    {
        public JobOwners()
        {
            this.Appointments = new HashSet<Appointments>();
            this.Services = new HashSet<Services>();
            this.WorkingTimes = new HashSet<WorkingTimes>();
        }
    
        public int Id { get; set; }
        public int UserId { get; set; }
        public int JobId { get; set; }
    
        public virtual ICollection<Appointments> Appointments { get; set; }
        public virtual Jobs Jobs { get; set; }
        public virtual Users Users { get; set; }
        public virtual ICollection<Services> Services { get; set; }
        public virtual ICollection<WorkingTimes> WorkingTimes { get; set; }
    }
}
