//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyAppointer.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Jobs
    {
        public Jobs()
        {
            this.JobOwners = new HashSet<JobOwners>();
        }
    
        public int Id { get; set; }

        [Required]
        [Display(Name = "Job Title")]
        public string Title { get; set; }

        [DataType(DataType.PhoneNumber)]
        [Display(Name = "Telephone Number")]
        [Required]

        [StringLength(11)]

        //^[01]?[- .]?(\([2-9]\d{2}\)|[2-9]\d{2})[- .]?\d{3}[- .]?\d{4}$
        [RegularExpression(@"^0-?[0-9]{10}$", ErrorMessage = "Enter Your Mobile Phone Number like this: 02433334346")]
 
        public string JobPhone { get; set; }
        public string About { get; set; }
        public string Address { get; set; }

        [Display(Name = "Job Type")]
        [Required]
        public int JobTypeId { get; set; }
        public int FirstJobOwner { get; set; }
    
        public virtual ICollection<JobOwners> JobOwners { get; set; }
        public virtual JobTypes JobTypes { get; set; }
        public virtual Users Users { get; set; }
    }
}
