//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyAppointer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jobs
    {
        public Jobs()
        {
            this.JobOwners = new HashSet<JobOwners>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string JobPhone { get; set; }
        public string About { get; set; }
        public string Address { get; set; }
        public int JobTypeId { get; set; }
        public int FirstJobOwner { get; set; }
    
        public virtual ICollection<JobOwners> JobOwners { get; set; }
        public virtual Users Users { get; set; }
        public virtual JobTypes JobTypes { get; set; }
    }
}
