//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyAppointer.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MyAppointerEntities : DbContext
    {
        public MyAppointerEntities()
            : base("name=MyAppointerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Appointments> Appointments { get; set; }
        public DbSet<JobOwners> JobOwners { get; set; }
        public DbSet<Jobs> Jobs { get; set; }
        public DbSet<JobTypes> JobTypes { get; set; }
        public DbSet<OffDays> OffDays { get; set; }
        public DbSet<Services> Services { get; set; }
        public DbSet<Users> Users { get; set; }
        public DbSet<WeeklyWorkingDays> WeeklyWorkingDays { get; set; }
        public DbSet<WeeklyWorkingTimes> WeeklyWorkingTimes { get; set; }
        public DbSet<WorkingTimes> WorkingTimes { get; set; }
    }
}
