//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyAppointer.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations; 

    public partial class Users
    {
        public Users()
        {
            this.Appointments = new HashSet<Appointments>();
            this.JobOwners = new HashSet<JobOwners>();
            this.Jobs = new HashSet<Jobs>();
        }
    
        public int Id { get; set; }


        [Required]
        [EmailAddress]
        [StringLength(32)]
        public string Email { get; set; }


        [Required]
        [DataType(DataType.Password)]
        [StringLength(64, MinimumLength = 6)]
        public string Password { get; set; }


        [DataType(DataType.PhoneNumber)]
        [Display(Name = "Mobile")]
        [Required]

        [StringLength(11)]

        //^[01]?[- .]?(\([2-9]\d{2}\)|[2-9]\d{2})[- .]?\d{3}[- .]?\d{4}$
        [RegularExpression(@"^09(1[0-9]|3[1-9]|2[1-9])-?[0-9]{7}$", ErrorMessage = "Enter Your Mobile Phone Number like this: 09127404062")]
        public string Phone { get; set; }

        [Required]
        [Display(Name = "Your First Name and Last Name")]
        public string FullName { get; set; }
        public string About { get; set; }

        [Required]
        public string City { get; set; }
        public string Role { get; set; }
        //public class DropdownViewModel
        //{
        //    public SelectList CarChoice { get; set; }
        //}
    
        public virtual ICollection<Appointments> Appointments { get; set; }
        public virtual ICollection<JobOwners> JobOwners { get; set; }
        public virtual ICollection<Jobs> Jobs { get; set; }
    }
}
