//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyAppointer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkingTimes
    {
        public WorkingTimes()
        {
            this.OffDays = new HashSet<OffDays>();
            this.WeeklyWorkingDays = new HashSet<WeeklyWorkingDays>();
            this.WeeklyWorkingTimes = new HashSet<WeeklyWorkingTimes>();
        }
    
        public int Id { get; set; }
        public int JobOwnerId { get; set; }
    
        public virtual JobOwners JobOwners { get; set; }
        public virtual ICollection<OffDays> OffDays { get; set; }
        public virtual ICollection<WeeklyWorkingDays> WeeklyWorkingDays { get; set; }
        public virtual ICollection<WeeklyWorkingTimes> WeeklyWorkingTimes { get; set; }
    }
}
